config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#home"

  get "dashboard", to: "dashboards#index", as: "dashboard"

  get "login", to: "sessions#new"
  get "logout", to: "sessions#destroy"
  post "login", to: "sessions#create"

  resources :users

  resources :stocks do
    collection do
      get "get_prices"
      get "prices"
    end
  end

  resources :transactions do
    collection do
      get "deposit", to: "transactions#deposit"
      get "withdraw", to: "transactions#withdraw"
      get "transfer", to: "transactions#transfer"

      post "deposit", to: "transactions#create_deposit"
      post "withdraw", to: "transactions#create_withdraw"
      post "transfer", to: "transactions#create_transfer"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deposit.rb
class Deposit < Transaction
  before_create :deposit

  private
  def deposit
    target_wallet.increment! :balance, amount.to_i
  end
end

app/models/stock.rb
class Stock < User

end

app/models/transaction.rb
class Transaction < ApplicationRecord
  # Associations
  belongs_to :source_wallet, class_name: "Wallet", optional: true
  belongs_to :target_wallet, class_name: "Wallet", optional: true
end

app/models/transfer.rb
class Transfer < Transaction
  before_create :transfer

  private
  def transfer
    source_wallet.decrement! :balance, amount.to_i
    target_wallet.increment! :balance, amount.to_i
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Scope
  default_scope { order(:name) }
  scope :active , -> { where(deleted: false, enabled: true) }

  # Associations
  has_one :wallet, -> { where(deleted: false, enabled: true) }, dependent: :destroy

  # Validations
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true
  validates :name, presence: true
  validates :user_type, presence: true
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :source_transactions, class_name: "Transaction", foreign_key: "source_wallet_id"
  has_many :target_transactions, class_name: "Transaction", foreign_key: "target_wallet_id"

  # Behavior
  def calculate_balance
    target_transactions.sum(:amount) - source_transactions.sum(:amount)
  end
end

app/models/withdrawal.rb
class Withdrawal < Transaction
  before_create :withdraw

  private
  def withdraw
    source_wallet.decrement! :balance, amount.to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user, except: [:home]
  include ActionController::Cookies

  def home
    if current_user
      redirect_to dashboard_path
    else
      redirect_to login_path
    end
	end

  private
  def current_user
    @current_user ||= (User.find(session[:user_id]) rescue nil) if session[:user_id]
  end

  def authenticate_user
    return if controller_name == "sessions" && action_name == "new"
    redirect_to "/login" unless current_user
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  layout 'application'

  def index

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user, only: [:new, :create]

  def create
    user = User.find_by(email: params[:email])
    if user && user.password == params[:password]
      session[:user_id] = user.id
      redirect_to "/dashboard"
    else
      flash[:error] = "Invalid email or password"
      redirect_to "/login"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/login"
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  require_relative '../../lib/latest_stock_price/latest_stock_price.rb'
  layout "transaction"

  before_action :set_section, except: [:get_prices]

  def set_section
    client = LatestStockPrice::Client.new
    @stocks = client.get_price_all.sort_by { |stock| stock[:identifier] }
  end

  def index
  end

  def prices
  end

  def get_prices
    client = LatestStockPrice::Client.new
    selected_stocks = params[:identifiers].reject { |i| i.empty? }.join(",")
    @stocks = client.get_prices(selected_stocks)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  layout "transaction"

  def deposit
    @transaction = Transaction.new
  end

  def withdraw
    @transaction = Transaction.new
  end

  def transfer
    @transaction = Transaction.new
    @targets = Wallet.joins(:user).where.not(wallets: { user_id: @current_user.id }).select("wallets.id, users.name")
  end

  def create_deposit
    # render json: params
    # return false
    ActiveRecord::Base.transaction do
      wallet = Wallet.find(params[:wallet_id])
      amount = params[:amount].to_f
      description = params[:description]

      raise ActiveRecord::Rollback, "Invalid amount" if amount <= 0

      Deposit.create!(
        target_wallet_id: wallet.id,
        amount: amount,
        transaction_type: "debit",
        status: "complete",
        description: description,
      )

      flash[:success] = "Successfully deposited #{amount} into your wallet"
      redirect_to deposit_transactions_path
    rescue ActiveRecord::RecordInvalid, ActiveRecord::Rollback => e
      flash[:error] = "Failed to deposit money: #{e.message}"
      redirect_to deposit_transactions_path
    end
  end

  def create_withdraw
    ActiveRecord::Base.transaction do
      wallet = Wallet.find(params[:wallet_id])
      amount = params[:amount].to_f
      description = params[:description]

      raise ActiveRecord::Rollback, "Invalid amount" if amount <= 0
      raise ActiveRecord::Rollback, "Insufficient balance" if wallet.balance < amount

      Withdrawal.create!(
        source_wallet_id: wallet.id,
        amount: amount,
        transaction_type: "credit",
        status: "complete",
        description: description,
      )

      flash[:success] = "Successfully withdraw #{amount} into your wallet"
      redirect_to withdraw_transactions_path
    rescue ActiveRecord::RecordInvalid, ActiveRecord::Rollback => e
      flash[:error] = "Failed to withdraw money: #{e.message}"
      redirect_to withdraw_transactions_path
    end
  end

  def create_transfer
    ActiveRecord::Base.transaction do
      raise ActiveRecord::Rollback, "Invalid target wallet" if params[:target_wallet_id].blank?

      source = Wallet.find(params[:wallet_id])
      target = Wallet.find(params[:target_wallet_id])
      amount = params[:amount].to_f
      description = params[:description]

      raise ActiveRecord::Rollback, "Invalid amount" if amount <= 0
      raise ActiveRecord::Rollback, "Insufficient balance" if source.balance < amount

      Transfer.create!(
        source_wallet_id: source.id,
        target_wallet_id: target.id,
        amount: amount,
        transaction_type: "credit",
        status: "complete",
        description: description,
      )

      flash[:success] = "Successfully transfer #{amount} from #{source.user.name} to #{target.user.name}"
      redirect_to transfer_transactions_path
    rescue ActiveRecord::RecordInvalid, ActiveRecord::Rollback => e
      flash[:error] = "Failed to transfer money: #{e.message}"
      redirect_to transfer_transactions_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type.to_sym
    when :notice
      "success"
    when :alert, :error
      "danger"
    else
      "info"
    end
  end

  def to_currency number, unit="", precision=0
    number_to_currency(number, :unit => unit, :precision => precision, :separator => ".", :delimiter => ",")
  end
end

app/views/dashboards/index.html.erb
<!-- Page Wrapper -->
<div id="wrapper">
  <%= render "layouts/nav" %>

  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <%= render "layouts/header" %>

          <!-- Begin Page Content -->
          <div class="container-fluid">

            <!-- Page Heading -->
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
              <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            </div>

            <!-- Content Row -->
            <div class="row">

              <!-- Earnings (Monthly) Card Example -->
              <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-success shadow h-100 py-2">
                  <div class="card-body">
                    <div class="row no-gutters align-items-center">
                      <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Balance</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= to_currency(@current_user.wallet.balance.to_f, "Rp. ", 2) %></div>
                      </div>
                      <div class="col-auto">
                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <%= render 'layouts/footer' %>

  </div>
  <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
              </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
              <a class="btn btn-primary" href="<%= logout_path %>">Logout</a>
          </div>
      </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Rahmad Riyadi 2024</span>
    </div>
  </div>
</footer>
<!-- End of Footer -->

app/views/layouts/_header.html.erb
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">
    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= @current_user.name %></span>
        <img class="img-profile rounded-circle" src="<%= asset_path('undraw_profile.svg') %>">
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Logout
        </a>
      </div>
    </li>
  </ul>
</nav>
<!-- End of Topbar -->

app/views/layouts/_nav.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Ataskwallet</div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item <%=  current_page?(dashboard_path) ? 'active' : '' %>">
    <a class="nav-link" href="<%= dashboard_path %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span>
    </a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading - Transactions -->
  <div class="sidebar-heading">
    Transactions
  </div>

  <!-- Nav Items -->
  <li class="nav-item <%=  current_page?(deposit_transactions_path) ? 'active' : '' %>">
    <a class="nav-link" href="<%= deposit_transactions_path %>">
      <i class="fas fa-fw fa-money-bill-alt"></i>
      <span>Deposit</span></a>
  </li>

  <li class="nav-item <%=  current_page?(withdraw_transactions_path) ? 'active' : '' %>">
    <a class="nav-link" href="<%= withdraw_transactions_path %>">
      <i class="fas fa-fw fa-money-bill-alt"></i>
      <span>Withdraw</span></a>
  </li>

  <li class="nav-item <%=  current_page?(transfer_transactions_path) ? 'active' : '' %>">
    <a class="nav-link" href="<%= transfer_transactions_path %>">
      <i class="fas fa-fw fa-money-bill-alt"></i>
      <span>Transfer</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading - Transactions -->
  <div class="sidebar-heading">
    Stocks
  </div>

  <!-- Nav Items -->
  <li class="nav-item <%=  current_page?(stocks_path) ? 'active' : '' %>">
    <a class="nav-link" href="<%= stocks_path %>">
      <i class="fas fa-fw fa-coins"></i>
      <span>Stocks List</span></a>
  </li>

  <!-- Nav Items -->
  <li class="nav-item <%=  current_page?(prices_stocks_path) ? 'active' : '' %>">
    <a class="nav-link" href="<%= prices_stocks_path %>">
      <i class="fas fa-fw fa-coins"></i>
      <span>Stock Prices</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>
<!-- End of Sidebar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ataskwallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "fontawesome-free/css/all.min", rel: "stylesheet", type: "text/css" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i", rel: "stylesheet" %>
    <%= stylesheet_link_tag "select2", "data-turbo-track": "reload", media: "all" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", "media": "all" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/transaction.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ataskwallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "fontawesome-free/css/all.min", rel: "stylesheet", type: "text/css" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i", rel: "stylesheet" %>
    <%= stylesheet_link_tag "select2", "data-turbo-track": "reload", media: "all" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", "media": "all" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="wrapper">
      <%= render "layouts/nav" %>

      <div id="content" class="w-100">
        <%= render "layouts/header" %>

        <% flash.each do |key, message| %>
          <div class="alert alert-<%= bootstrap_class_for_flash(key) %> alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/stocks/get_prices.html.erb
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">Stock Prices</h1>

  <!-- DataTales -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Stock Prices</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th width="20%">Identifier</th>
              <th width="20%">Company</th>
              <th width="20%">Industry</th>
              <th>ISIN</th>
              <th class="text-right">Last Price</th>
              <th>Last Update</th>
            </tr>
          </thead>
          <tbody>
            <% total = 0 %>
            <% @stocks.each do |stock| %>
              <% total += stock[:lastPrice].to_f %>
              <tr>
                <td><%= stock[:identifier] %></td>
                <td><%= stock[:meta][:companyName] %></td>
                <td><%= stock[:meta][:industry] %></td>
                <td><%= stock[:meta][:isin] %></td>
                <td class="text-right"><%= to_currency(stock[:lastPrice].to_f, '', 2) %></td>
                <td><%= stock[:lastUpdateTime] %></td>
              </tr>
            <% end %>
          </tbody>
          <tfoot>
            <tr>
              <th colspan="4" class="text-right">Total</th>
              <th colspan="2" class="text-right"><%= to_currency(total, '', 2) %></th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/stocks/index.html.erb
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">Stocks List</h1>

  <!-- DataTales -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Stocks List</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th width="20%">Identifier</th>
              <th width="20%">Company</th>
              <th width="20%">Industry</th>
              <th>ISIN</th>
              <th class="text-right">Last Price</th>
              <th>Last Update</th>
            </tr>
          </thead>
          <tbody>
            <% total = 0 %>
            <% @stocks.each do |stock| %>
              <% total += stock[:lastPrice].to_f %>
              <tr>
                <td><%= stock[:identifier] %></td>
                <td><%= stock[:meta][:companyName] %></td>
                <td><%= stock[:meta][:industry] %></td>
                <td><%= stock[:meta][:isin] %></td>
                <td class="text-right"><%= to_currency(stock[:lastPrice].to_f, '', 2) %></td>
                <td><%= stock[:lastUpdateTime] %></td>
              </tr>
            <% end %>
          </tbody>
          <tfoot>
            <tr>
              <th colspan="4" class="text-right">Total</th>
              <th colspan="2" class="text-right"><%= to_currency(total, '', 2) %></th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/stocks/prices.html.erb
<div class="container">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Stock Prices</h6>
    </div>
    <div class="card-body">
      <%= form_with url: get_prices_stocks_path, method: :get, local: true, class: "stock" do |f| %>
        <div class="form-group">
          <%= f.label :identifiers, "Recipient", class: "form-label" %>
          <%= f.select :identifiers, 
            options_for_select(@stocks.map { |stock| [stock[:identifier], stock[:identifier]] }), 
            { prompt: "Select stocks" }, 
            class: "form-control select2", multiple: true %>
        </div>

        <div class="form-group">
          <%= f.submit "Get Prices", class: "btn btn-primary btn-user btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/transactions/deposit.html.erb
<div class="container">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Deposit Money</h6>
    </div>
    <div class="card-body">
      <%= form_with url: deposit_transactions_path, method: :post, local: true, class: "user" do |f| %>
        <div class="form-group">
          <%= f.label :amount, "Deposit Amount", class: "form-label" %>
          <%= f.text_field :amount, class: "form-control currency", placeholder: "Enter amount" %>
        </div>

        <div class="form-group">
          <%= f.label :description, "Description (optional)", class: "form-label" %>
          <%= f.text_area :description, class: "form-control", rows: 3, placeholder: "E.g., Adding funds for future purchases" %>
        </div>
        <%= f.hidden_field :wallet_id, value: @current_user.wallet.id %>

        <div class="form-group">
          <%= f.submit "Deposit", class: "btn btn-primary btn-user btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/transactions/transfer.html.erb
<div class="container">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Transfer Money</h6>
    </div>
    <div class="card-body">
      <%= form_with url: transfer_transactions_path, method: :post, local: true, class: "user" do |f| %>
        <!-- Select recipient -->
        <div class="form-group">
          <%= f.label :target_wallet_id, "Recipient", class: "form-label" %>
          <%= f.select :target_wallet_id, 
            options_from_collection_for_select(@targets, :id, :name), 
            { prompt: "Select recipient" }, 
            class: "form-control select2" %>
        </div>
        
        <div class="form-group">
          <%= f.label :amount, "Transfer Amount", class: "form-label" %>
          <%= f.text_field :amount, class: "form-control currency", placeholder: "Enter amount", data: { autonumeric: true } %>
        </div>

        <div class="form-group">
          <%= f.label :description, "Description (optional)", class: "form-label" %>
          <%= f.text_area :description, class: "form-control", rows: 3, placeholder: "E.g., Adding funds for future purchases" %>
        </div>
        <%= f.hidden_field :wallet_id, value: @current_user.wallet.id %>

        <div class="form-group">
          <%= f.submit "Transfer", class: "btn btn-primary btn-user btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/transactions/withdraw.html.erb
<div class="container">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Withdraw Money</h6>
    </div>
    <div class="card-body">
      <%= form_with url: withdraw_transactions_path, method: :post, local: true, class: "user" do |f| %>
        <div class="form-group">
          <%= f.label :amount, "Withdraw Amount", class: "form-label" %>
          <%= f.text_field :amount, class: "form-control currency", placeholder: "Enter amount" %>
        </div>

        <div class="form-group">
          <%= f.label :description, "Description (optional)", class: "form-label" %>
          <%= f.text_area :description, class: "form-control", rows: 3, placeholder: "E.g., Adding funds for future purchases" %>
        </div>
        <%= f.hidden_field :wallet_id, value: @current_user.wallet.id %>

        <div class="form-group">
          <%= f.submit "Withdraw", class: "btn btn-primary btn-user btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>